name: Daily LeetCode Sync to Notion

on:
  schedule:
    - cron: '30 13 * * *'  # Runs every day at 6:00 PM IST (13:30 UTC)
  workflow_dispatch:       # Allows manual run from GitHub Actions tab

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run sync script
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
          LEETCODE_USERNAME: ${{ secrets.LEETCODE_USERNAME }}
        run: python sync.py
